"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import {
  cashbookTransactionSchema,
  type CashbookTransactionFormValues,
} from "@/lib/validators/cashbook-transaction";

export async function getTransactions(cashbookDayId: string) {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("cashbook_transactions")
    .select("*")
    .eq("cashbook_day_id", cashbookDayId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return data || [];
}

export async function getTransaction(id: string) {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("cashbook_transactions")
    .select("*")
    .eq("id", id)
    .single();

  if (error) throw error;
  return data;
}

export async function getTransactionRevisions(transactionId: string) {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("transaction_revisions")
    .select("*, changed_by_profile:user_profiles!changed_by(full_name)")
    .eq("transaction_id", transactionId)
    .order("revision_number", { ascending: false });

  if (error) throw error;
  return data || [];
}

export async function createTransaction(
  values: CashbookTransactionFormValues & {
    cashbook_id: string;
    cashbook_day_id: string;
    company_id: string;
    branch_id: string;
    financial_year_id?: string;
    created_by: string;
  }
) {
  const validated = cashbookTransactionSchema.parse(values);
  const supabase = await createClient();

  // Receipt number and hash are generated by the DB trigger (generate_receipt_number_and_hash)
  // We pass a placeholder receipt_number — the trigger replaces it
  const { error } = await supabase.from("cashbook_transactions").insert({
    cashbook_id: values.cashbook_id,
    cashbook_day_id: values.cashbook_day_id,
    company_id: values.company_id,
    branch_id: values.branch_id,
    financial_year_id: values.financial_year_id || null,
    txn_type: validated.txn_type,
    amount: validated.amount,
    payment_mode: validated.payment_mode,
    narration: validated.narration,
    contra_cashbook_id: validated.contra_cashbook_id || null,
    receipt_number: "PENDING", // Trigger generates this
    receipt_hash: "PENDING", // Trigger generates this
    created_by: values.created_by,
  });

  if (error) return { error: error.message };

  revalidatePath("/cash/cashbooks");
  return { success: true };
}

/**
 * Create a transaction for bulk import — auto-finds or opens a cashbook day.
 */
export async function createTransactionForImport(
  values: {
    cashbook_id: string;
    date: string;
    txn_type: "receipt" | "payment";
    amount: number;
    payment_mode: "cash" | "cheque" | "upi" | "bank_transfer" | "card" | "finance";
    narration: string;
    party_name: string;
    company_id: string;
    branch_id: string;
    financial_year_id?: string;
    created_by: string;
  }
) {
  const supabase = await createClient();

  // Find or error on cashbook day
  const { data: day, error: dayError } = await supabase
    .from("cashbook_days")
    .select("id, status")
    .eq("cashbook_id", values.cashbook_id)
    .eq("date", values.date)
    .in("status", ["open", "reopened"])
    .single();

  if (dayError || !day) {
    return {
      error: `No open cashbook day found for date ${values.date}. Please open the day first from the Cashbooks section.`,
    };
  }

  const { error } = await supabase.from("cashbook_transactions").insert({
    cashbook_id: values.cashbook_id,
    cashbook_day_id: day.id,
    company_id: values.company_id,
    branch_id: values.branch_id,
    financial_year_id: values.financial_year_id || null,
    txn_type: values.txn_type,
    amount: values.amount,
    payment_mode: values.payment_mode,
    narration: values.narration,
    party_name: values.party_name,
    receipt_number: "PENDING",
    receipt_hash: "PENDING",
    created_by: values.created_by,
  });

  if (error) return { error: error.message };

  revalidatePath("/cash/cashbooks");
  return { success: true };
}

export async function voidTransaction(
  id: string,
  voidReason: string,
  voidedBy: string
) {
  const supabase = await createClient();

  const { error } = await supabase
    .from("cashbook_transactions")
    .update({
      is_voided: true,
      void_reason: voidReason,
      voided_by: voidedBy,
      voided_at: new Date().toISOString(),
    })
    .eq("id", id);

  if (error) return { error: error.message };

  revalidatePath("/cash/cashbooks");
  return { success: true };
}
