-- ============================================================
-- Migration 019: Add party_name to cashbook_transactions,
--                Create customers table, link to invoices
-- ============================================================

-- ── 1. party_name column on cashbook_transactions ────────────
ALTER TABLE cashbook_transactions
  ADD COLUMN IF NOT EXISTS party_name TEXT;

-- ── 2. Customers table ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    branch_id       UUID REFERENCES branches(id) ON DELETE SET NULL,
    customer_code   TEXT NOT NULL DEFAULT '',  -- auto-generated by trigger
    full_name       TEXT NOT NULL,
    phone           TEXT,
    email           TEXT,
    address         TEXT,
    city            TEXT,
    state           TEXT,
    pincode         TEXT,
    gstin           TEXT,
    pan             TEXT,
    customer_type   TEXT NOT NULL DEFAULT 'individual',  -- individual | business
    notes           TEXT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_by      UUID REFERENCES user_profiles(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (company_id, customer_code)
);

-- Auto-generate customer_code trigger
CREATE OR REPLACE FUNCTION generate_customer_code()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    v_next  BIGINT;
BEGIN
    SELECT COALESCE(MAX(
        CASE WHEN customer_code ~ '^CUST-[0-9]+$'
             THEN CAST(SUBSTRING(customer_code FROM 6) AS BIGINT)
             ELSE 0
        END
    ), 0) + 1
      INTO v_next
      FROM customers
     WHERE company_id = NEW.company_id;

    NEW.customer_code := 'CUST-' || LPAD(v_next::TEXT, 4, '0');
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_generate_customer_code
BEFORE INSERT ON customers
FOR EACH ROW
EXECUTE FUNCTION generate_customer_code();

-- updated_at trigger for customers
CREATE OR REPLACE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── 3. Link customers to invoices ────────────────────────────
ALTER TABLE invoices
  ADD COLUMN IF NOT EXISTS customer_id UUID REFERENCES customers(id) ON DELETE SET NULL;

-- ── 4. RLS on customers ──────────────────────────────────────
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "customers_company_isolation" ON customers
  FOR ALL USING (
    company_id IN (
      SELECT DISTINCT ua.company_id
        FROM user_assignments ua
       WHERE ua.user_id = auth.uid()
         AND ua.company_id IS NOT NULL
    )
  );

-- ── 5. Indexes ───────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_customers_company_id    ON customers(company_id);
CREATE INDEX IF NOT EXISTS idx_customers_code          ON customers(company_id, customer_code);
CREATE INDEX IF NOT EXISTS idx_customers_phone         ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id    ON invoices(customer_id);

-- ── 6. Reload PostgREST schema cache ─────────────────────────
NOTIFY pgrst, 'reload schema';
